### ISSUE TITLE
Please re-publish also 0.0.3 version. 

### ISSUE THREAD

**Issue by GianlucaMaggio** [xmlking/ngx-starter-kit#163]
Please re-publish also 0.0.3 version. We have a dependency on that version because we maintain all the previous version of our software and the latest one (0.0.7) is not compatible with angular 7.2.6.

Anyway consider that removing something from npm is considered a bad practice because people can depend on any version published (https://docs.npmjs.com/cli/unpublish).

Thanks

_Originally posted by @GianlucaMaggio in https://github.com/xmlking/ngx-starter-kit/issues/156#issuecomment-531825965_

**Comment by xmlking** [comment]
sorry for the inconvenience. I had to consolidate my NPM accounts under one Org account, and npm helpdesk suggested deleting    `ngx-starter-kit` account and recreate as scope under my Org account.  
will it be possible for you to send me zip of 0.0.3 version?  I don't  have backups unfortunately
I will explore  how i can get  `0.0.3`  and  republish.

**Comment by GianlucaMaggio** [comment]
Sure, I send it to you by e-mail.
Thanks

**Comment by GianlucaMaggio** [comment]
Thank you

Sent from Mail for Windows 10

**Comment by GianlucaMaggio** [comment]
[@ngx-starter-kit.zip](https://github.com/xmlking/ngx-starter-kit/files/3619493/%40ngx-starter-kit.zip)

Better here, maybe.

**Comment by xmlking** [comment]
published your zip as 0.0.3-rc1  (I cannot use  0.0.3 version as NPM is not allowing me)
I also published 0.0.8 which is tested  with angular 8.2.x
