### ISSUE TITLE
Issue running commit script

### ISSUE THREAD

**Issue by orlaqp** [xmlking/ngx-starter-kit#18]
First of all, I want to say that this kit you put together here its AWESOME and I have learned a lot about many packages and architectural points using it, THANK YOU!

I wanted to mention an issue I was having though and it is related the this command:

`yarn commit`

Once you enter all the information it never completed the first step of `lint-stage`. It never complete this command:

yarn affected:lint --uncommitted --parallel

If I run it separately it runs correctly but not when called using `lint-stage`. Do I need to setup anything before run this command?

**Comment by xmlking** [comment]
I opened this issue with nx and lint-stage

https://github.com/nrwl/nx/issues/869
https://github.com/okonet/lint-staged/issues/522

temporary workaround 
1.  skip git hooks ([doc](https://github.com/xmlking/ngx-starter-kit/blob/develop/stories/howto.md) )
```
# skip git hooks with 
git cz --no-verify # assume you install `commitizen` globally (`npm install -g commitizen`)
```

**OR**

2. in package.json 
change  `npm run affected:lint  -- --uncommitted --fix --parallel` to   `yarn affected:lint --uncommitted`

**Comment by orlaqp** [comment]
Thank you! I will keep on eye on the issue you opened

**Comment by xmlking** [comment]
Now i also have `"prepare-commit-msg": "exec < /dev/tty && git cz --hook",`  git hook.
So `git commit --no-verify`    also prompt [commitizen](https://github.com/commitizen/cz-cli)
