### ISSUE TITLE
Demo Link not working

### ISSUE THREAD

**Issue by johannesschobel** [xmlking/ngx-starter-kit#24]
Dear @xmlking ,

first of all - from what i have seen from the code, this looks f*cking amazing! WOW! :tada: 
Unfortunately i was not able to see it in action - the demo link is constantly loading. Further, it shows some errors in the console..

All the best!

**Comment by xmlking** [comment]
Thanks for feedback.  The Open ID Auth server (keycloak) is down as my free trail for OpenShift hosting ended. 
I will move to new server soon so we will have uninterrupted service :)

**Comment by xmlking** [comment]
fixed now. reload demo site  to evict cache.

**Comment by johannesschobel** [comment]
Thank you very much for your fast reply this.  I will try it on Sunday :) appreciate your time and work
