### ISSUE TITLE
Safari freezed with InViewport directive

### ISSUE THREAD

**Issue by notarnet** [xmlking/ngx-starter-kit#27]
Hi,
I'm using the **InViewport** directive in my app, but when I run it on **Safari** the browser is freezed and I can only Force quit. I tried to use **IntersectionObserver** polyfill, as written in the doc, but it does not resolve the issue.

**Comment by xmlking** [comment]
I am testing with [demo](https://xmlking.github.io/ngx-starter-kit/dashboard/experiments/viewport)  with  `Safari Version 12.0.2`  MacOS High Sierra `v10.13.6` and it works fine.

could you provide your safari/macOS version.
Also would be helpful if you share your code example via stackblitz.com

**Comment by notarnet** [comment]
My application have a very complex DOM and in Safari, the intersection observer polyfill, cannot manage that complexity efficiently.

I solved ignoring DOM changes in polyfill with the following code:
`import 'intersection-observer';`
`IntersectionObserver.prototype["USE_MUTATION_OBSERVER"] = false;`
