### ISSUE TITLE
combineLatest deprecated 

### ISSUE THREAD

**Issue by macliems** [xmlking/ngx-starter-kit#3]
My Webstorm editor warns that `combineLatest` in router.state.ts (line 42) is deprecated ....

**Comment by xmlking** [comment]
we are using  the static version and not the pipeable operator.  
`import {combineLatest} from "rxjs";`
may be `Webstorm's` false alert.

**Comment by xmlking** [comment]
custom `router.state.ts`  is replaced with `ngxs` router plugin.
