### ISSUE TITLE
How to configure & debug using vscode?

### ISSUE THREAD

**Issue by olakara** [xmlking/ngx-starter-kit#36]
I am struggling to debug (use breakpoints and inspect the application flow) using vscode. Can someone share me how to configure the debug. I have tried multiple solutions available after googling. But all of them are not in Nx Workspace or with Angular. 

Can some one share the launch.json / nodemon-debug.json or other related files for debugging?

Thanks

**Comment by xmlking** [comment]
I am not actively using `vscode` yet.  you may get better answer if you post in `nrwl/nx` project.

**Comment by olakara** [comment]
thanks, I will try at `nrwl/nx` :)
