### ISSUE TITLE
Yarn Install Error

### ISSUE THREAD

**Issue by johannesschobel** [xmlking/ngx-starter-kit#73]
When cloning the package and simply run 
```
yarn install
```

the following file (`./.npmrc`) throws an error..

https://github.com/xmlking/ngx-starter-kit/blob/eff9ad5655a8b3261b87c0169d7e93a7e9a43bb4/.npmrc#L1

This is because the comment in the `./.npmrc` file should be `#` and not `//` i guess?!

All the best

**Comment by xmlking** [comment]
You can delete this file, I was using this with NPM_TOKEN environment variable in my .profile ,to publish libs  to npm

**Comment by johannesschobel** [comment]
thanks for the clarification ;) closed
