### ISSUE TITLE
Unable to generate application

### ISSUE THREAD

**Issue by jkosters** [xmlking/ngx-starter-kit#9]
No matter what I try, I can't seem to generate a new application in the repo. There is no error or any other output and no files are created. When creating a workspace from scratch seems to work fine, until I update angular core. Does that mean that I need to wait for a fix from nx or add it manually just like issue #8  ?

(Love the repo btw, learning a lot from it. )

**Comment by xmlking** [comment]
I updated repo with latest #nx
you may not able able to create **lazy routing** module yet,
```
ng g lib grid           --routing --lazy --prefix=ngx --parent-module=libs/dashboard/src/lib/dashboard.module.ts   --tags=child-module
```
But  you can create normal module.  
```
ng g lib gridmap --prefix=ngx --tags=child-module
```
Then you can add routing manually based on other  lazy routing modules examples I have in this repo.

https://github.com/nrwl/nx/issues/310

**Comment by xmlking** [comment]
this should work with latest code.
Please  pull latest code and let me know

**Comment by jkosters** [comment]
Thank you. As I said; great work on the repo.
